### ISSUE TITLE
a little request

### ISSUE THREAD

**Issue by mobeicanyue** [vasttian/lottery#1]
大佬您好，我想离线使用这个网页，请问怎么操作呢。我下载了源代码，但是打开页面是空白的。

**Comment by vasttian** [comment]
抱歉啊，我才看见。
请问现在可以离线访问了吗？

离线访问可以在本地起个开发服务，或者 build 后在本地用 Nginx 之类的起个服务。

**Comment by vasttian** [comment]
> 大佬您好，我想离线使用这个网页，请问怎么操作呢。我下载了源代码，但是打开页面是空白的。


抱歉啊，我才看见。
请问现在可以离线访问了吗？

离线访问可以在本地起个开发服务，或者 build 后在本地用 Nginx 之类的起个服务。

**Comment by mobeicanyue** [comment]
还要开服务器吗🤣好吧



---Original---
From: ***@***.***&gt;
Date: Wed, Dec 29, 2021 12:04 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [vasttian/lottery] a little request (#1)




 
抱歉啊，我才看见。
 请问现在可以离线访问了吗？
 
离线访问可以在本地起个开发服务，或者 build 后在本地用 Nginx 之类的起个服务。

**Comment by vasttian** [comment]
> 还要开服务器吗🤣好吧
> […](#)
> ---Original--- From: ***@***.***&gt; Date: Wed, Dec 29, 2021 12:04 PM To: ***@***.***&gt;; Cc: ***@***.***&gt;;"State ***@***.***&gt;; Subject: Re: [vasttian/lottery] a little request (#1) 抱歉啊，我才看见。 请问现在可以离线访问了吗？ 离线访问可以在本地起个开发服务，或者 build 后在本地用 Nginx 之类的起个服务。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: ***@***.***&gt;

在本地起个前端服务就可以啦，就和你平时开发一样

**Comment by mobeicanyue** [comment]
好的。我试试

**Comment by mobeiCanyue** [comment]
老哥, 我想知道你是怎么在github上部署的动态网站, 能给个联系方式吗, 或者我的richarsdo233@gmail.com

**Comment by vasttian** [comment]
> 老哥, 我想知道你是怎么在github上部署的动态网站, 能给个联系方式吗, 或者我的[richarsdo233@gmail.com](mailto:richarsdo233@gmail.com)

是用 GitHub Pages 部署的静态

**Comment by mobeicanyue** [comment]
好吧，那没事了
